### PR TITLE
[Regex] Match and return regex captured groups

### PR DESCRIPTION
**Pull request by notbenoit**
### Goals :soccer:
Add a function on `Regex` to match and return captured groups (if any)
This can be needed in some instances, when extracting some specific content from a string (eg: a timestamp)

### Implementation Details :construction:
The function simply iterates over all `NSTextCheckingResult` and pull out captured groups for every single match.

### Note
Should this PR increment the podspec version as well ? `2.1.0` for such a simple addition ?

### CODE REVIEW

**Comment by leontiy** [comment]
@notbenoit it looks like the result might be a bit too flat. :) Suppose we have multiple matches with multiple groups in each. How do we address specific groups within each match?

In my mind, it would be optimal not to flatten the resulting groups and return an array of matches, each with an associated array of groups. (however you choose to model those).

**Comment by notbenoit** [comment]
Good point @leontiy . I'll un-flatten this and leave the matched groups per match (`[[String]]`). It will be the caller's responsability to flatten this or not.

**Comment by notbenoit** [comment]
Updated to un-flatten the whole result. It's indeed more "correct" to keep the groups in the match occurence they belong to.

**Review by leontiy — APPROVED** [review]

**Review by stephanecopin — APPROVED** [review]
Merging this as it's been updated, and works as expected 💯

**Pull request merged**
