### PR TITLE
feat(alertview): add alert view and action sheet support in swiftUI

### PR DESCRIPTION
**Pull request by ghost**
## Description:

1.  Adding alert view and action sheet support in SwiftUI.

## Code Usage:

```swift
import SwiftUI
import FueledUtilsSwiftUI

struct ContentView: View {
	@State private var showAlertModal = false
	@State private var showActionSheet = false

	let alertModel = AlertModel(
		title: "Alert Title",
		message: "Alert Message",
		buttons: [
			AlertButton(title: "Okay", action: {
				print("Okay")
			}),
			AlertButton(title: "Cancel", action: {
				print("Cancel")
			})
		]
	)

	let actionSheetModel = AlertModel(
		title: "Action Sheet Title",
		message: "Action Sheet Message",
		buttons: [
			AlertButton(title: "Option 1", action: {
				print("Option 1")
			}),
			AlertButton(title: "Option 2", action: {
				print("Option 2")
			}),
			AlertButton(title: "Option 3", action: {
				print("Option 3")
			})
		]
	)

	var body: some View {
		VStack {
			Spacer()
			Image(systemName: "globe")
				.imageScale(.large)
				.foregroundColor(.accentColor)
			Text("Show Alert")
				.foregroundColor(.white)
				.padding()
				.background(Color.black)
				.onTapGesture {
					showAlertModal.toggle()
				}
			Text("Show Action Sheet")
				.foregroundColor(.white)
				.padding()
				.background(Color.black)
				.onTapGesture {
					showActionSheet.toggle()
				}
			HStack {
				Spacer()
			}
			Spacer()
		}
		.background(Color.white)
		.showAlert(alertModel: alertModel, isPresented: $showAlertModal)
		.showAlert(
			alertModel: actionSheetModel,
			presentationStyle: .bottomSheet(titleVisibility: .visible),
			isPresented: $showActionSheet
		)
	}
}
```

### CODE REVIEW

**Review by vinaykharb — APPROVED** [review]
Looks good!!

**Review by harishsaini — APPROVED** [review]
looks good 👍

**Comment by jeffpaul** [comment]
a bit dated but @metatheoretic seems like this might be approved and ready to merge?

**Comment by harishsaini** [comment]
@jeffpaul imo we should be good to merge this one.

**Comment by hadiidbouk** [comment]
@jeffpaul  We had a discussion earlier regarding whether this approach is helpful, and most of the team agrees that we shouldn't allow this pattern since it may vary between projects. Additionally, the APIs are outdated.

I will close this PR.

**Pull request closed without merging**
